---
# NetQ only supported on Cumulus 3.3+
- name: Check Cumulus version
  fail:
    msg: "NetQ is only supported on Cumulus versions 3.3 and later"
  when: ansible_lsb.release is version_compare('3.3', '<')

- name: Remove any old netq repos
  apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 {{ item }}
    state: absent
  with_items:
    - 'netq-1.4'
    - 'netq-2.4'
    - 'netq-3.0'

- name: Add netq repo
  apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 {{ netq_repo }}
    state: present

# The netq package installs addtional config to rsyslog
- name: Install netq agent
  apt:
    name: ['netq-agent', 'netq-apps']
    update_cache: yes
    state: latest
  notify: restart rsyslog

- name: Configure netq agent
  copy:
    content: "{{ netq_backend_config|to_nice_yaml }}"
    dest: /etc/netq/config.d/netq.yml
  notify: restart netq
